Update docker-build.yml
Signed-off-by: bhumi46 <111699703+bhumi46@users.noreply.github.com>

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -124,21 +124,6 @@ jobs:
       - name: Get current date
         run: echo "BUILD_TIME=$(date +'%Y-%m-%d-%H-%M-%S')"  >> $GITHUB_ENV
 
-      - name: Build check for Docker label
-        if: ${{ inputs.BASE_IMAGE_BUILD == false }}
-        run: |
-          cd ${{ inputs.SERVICE_LOCATION }}
-          for layer in  ARG\\s+SOURCE ARG\\s+COMMIT_HASH ARG\\s+COMMIT_ID ARG\\s+BUILD_TIME LABEL\\s+source=\\$\\{SOURCE\\} LABEL\\s+commit_hash=\\$\\{COMMIT_HASH\\} LABEL\\s+commit_id=\\$\\{COMMIT_ID\\} LABEL\\s+build_time=\\$\\{BUILD_TIME\\}; do
-            layer_count=$( grep -Ev '^$' Dockerfile | grep -Ec "$layer" || true);
-          
-            if [[ $layer_count -ne 1 ]]; then
-              dlayer=$( echo $layer | sed -E 's/\\s\+/ /g' | sed -E 's/\\//g' )
-              echo "Docker layer : \"$dlayer\" not found; EXITING";
-              exit 1;
-            fi
-          done
-          
-
       - name: Check Dockerfile for 'mosip' user definition
         run: |
           cd ${{ inputs.SERVICE_LOCATION }}
@@ -168,6 +153,30 @@ jobs:
                 exit 1
               fi
             done
+          done
+        if: ${{ inputs.BASE_IMAGE_BUILD == false }}
+
+      - name: Build check for Docker datetime & git commit labels
+        run: |
+          cd ${{ inputs.SERVICE_LOCATION }}
+           chk_layer=( "ARG\\s+SOURCE"
+                       "ARG\\s+COMMIT_HASH"
+                       "ARG\\s+COMMIT_ID"
+                       "ARG\\s+BUILD_TIME"
+                       "LABEL\\s+source=\\\${SOURCE}"
+                       "LABEL\\s+commit_hash=\\\${COMMIT_HASH}"
+                       "LABEL\\s+commit_id=\\\${COMMIT_ID}" 
+                       "LABEL\\s+build_time=\\\${BUILD_TIME}"
+          )
+          
+          for layer in "${chk_layer[@]}"; do
+            layer_count=$( grep -Ev '^$' Dockerfile | grep -Ec "$layer" || true);
+          
+            if [[ $layer_count -ne 1 ]]; then
+              dlayer=$( echo $layer | sed -E 's/\\s\+/ /g' | sed -E 's/\\//g' )
+              echo "Docker layer : \"$dlayer\" not found; EXITING";
+              exit 1;
+            fi
           done
         if: ${{ inputs.BASE_IMAGE_BUILD == false }}
           
