[MOSIP-25631] Updated workflows as per review changes requested

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -9,7 +9,7 @@ on:
       SERVICE_LOCATION:
         required: true
         type: string
-      BUILT_ARTIFACT:
+      BUILD_ARTIFACT:
         required: true
         type: string
       NPM_BUILD:
@@ -37,7 +37,7 @@ jobs:
       - uses: actions/checkout@v3
       - uses: actions/download-artifact@v3
         with:
-          name: ${{ inputs.BUILT_ARTIFACT }}
+          name: ${{ inputs.BUILD_ARTIFACT }}
           path: ./
 
       - name: Setup branch and env
@@ -56,20 +56,32 @@ jobs:
 
       - name: Unzip and extract for maven
         if: ${{ contains(inputs.NPM_BUILD, 'false') }}
-        run: unzip -uj "./${{ inputs.BUILT_ARTIFACT }}.zip" "${{ inputs.SERVICE_LOCATION }}/target/*" -d "./${{ inputs.SERVICE_LOCATION }}/target"
+        run: |
+          unzip -uj "./${{ inputs.BUILD_ARTIFACT }}.zip" "${{ inputs.SERVICE_LOCATION }}/target/*" -d "${{ env.SERVICE_LOCATION }}/target/"
 
       - name: Unzip and extract for npm
         if: ${{ contains(inputs.NPM_BUILD, 'true') }}
         run: |
-          mkdir -p "${{ inputs.SERVICE_LOCATION }}"
-          unzip "./${{ inputs.BUILT_ARTIFACT }}.zip" -d "${{ inputs.SERVICE_LOCATION }}"
+          unzip "./${{ inputs.BUILD_ARTIFACT }}.zip" "dist/*" -d "${{ inputs.SERVICE_LOCATION }}"
 
       - name: Get current date
         run: echo "BUILD_TIME=$(date +'%Y-%m-%d-%H-%M-%S')"  >> $GITHUB_ENV
 
+      - name: Build check for Docker label
+        run: |
+          cd ${{ inputs.SERVICE_LOCATION }}
+          for layer in  ARG\\s+SOURCE ARG\\s+COMMIT_HASH ARG\\s+COMMIT_ID ARG\\s+BUILD_TIME LABEL\\s+source=\\$\\{SOURCE\\} LABEL\\s+commit_hash=\\$\\{COMMIT_HASH\\} LABEL\\s+commit_id=\\$\\{COMMIT_ID\\} LABEL\\s+build_time=\\$\\{BUILD_TIME\\}; do
+            layer_count=$( grep -Ev '^$' Dockerfile | grep -Ec "$layer" || true);
+          
+            if [[ $layer_count -ne 1 ]]; then
+              dlayer=$( echo $i | sed -E 's/\\s\+/ /g' | sed -E 's/\\//g' )
+              echo "Docker layer : $dlayer not found; EXITING";
+            fi
+          done
+
       - name: Build image
         run: |
-          cd "./${{env.SERVICE_LOCATION}}"
+          cd ${{ inputs.SERVICE_LOCATION }}
           docker build . --build-arg SOURCE=mosip --build-arg COMMIT_HASH=$(git rev-parse HEAD) --build-arg COMMIT_ID=$(git rev-parse --short HEAD) --build-arg BUILD_TIME=$BUILD_TIME --file Dockerfile --tag ${{ env.SERVICE_NAME }}
 
       - name: Log into registry
@@ -95,7 +107,7 @@ jobs:
       - uses: 8398a7/action-slack@v3
         with:
           status: ${{ job.status }}
-          fields: repo,message,commit,workflow,job # selectable (default: repo,message)
+          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
         env:
           SLACK_WEBHOOK_URL: ${{ secrets.SLACK_DEVOPS_WEBHOOK }} # required
         if: failure() # Pick up events even if the job fails or is canceled. 
diff --git a/.github/workflows/gradlew-sonar-analysis.yml b/.github/workflows/gradlew-sonar-analysis.yml
--- a/.github/workflows/gradlew-sonar-analysis.yml
+++ b/.github/workflows/gradlew-sonar-analysis.yml
@@ -1,5 +1,4 @@
-name: Publish to NPM
-
+name: Sonar Analysis via Gradlew
 on:
   workflow_call:
     inputs:
@@ -7,19 +6,20 @@ on:
         description: 'SERVICE LOCATION'
         required: true
         type: string
-      GRADLEW_ARGS:
-        description: 'Provide gradlew arguments'
-        required: true
-        type: string
-    secrets:
-      NPM_AUTH_TOKEN:
-        required: true
 
+    secrets:
+      SONAR_TOKEN:
+        required: true
+      SONAR_ORGANIZATION:
+        required: true
 env:
   ANDROID_HOME: '/opt/android-sdk/'
+  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
+  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+  SONAR_ORGANIZATION: ${{ secrets.SONAR_ORGANIZATION }}
 
 jobs:
-  gradlew-publish-to-npm-registry:
+  gradlew-sonar-analysis:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout Repository
@@ -52,32 +52,32 @@ jobs:
       - name: npm Install
         run: cd ${{ inputs.SERVICE_LOCATION }} && npm install
 
-      - name: Build APK via Gradlew
+      - name: Check if Environmental variables set for sonar
+        run: | 
+          if [[ -z $SONAR_TOKEN ]]; then
+            echo "\$SONAR_TOKEN environmental variable not set; EXITING;";
+            exit 1;
+          fi
+          if [[ -z $SONAR_ORGANIZATION ]]; then
+            echo "\$SONAR_ORGANIZATION environmental variable not set; EXITING;";
+            exit 1;
+          fi
+          if [[ -z $SONAR_URL ]]; then
+            echo "\$SONAR_URL environmental variable not set; EXITING;";
+            exit 1;
+          fi
+
+      - name: Analysis with Sonarcloud
         run: |
-          cd ${{ inputs.SERVICE_LOCATION }}/android
+          cd ${{ inputs.SERVICE_LOCATION }}
           sed -i -e 's/\r$//' ./gradlew
           chmod +x ./gradlew
-          ./gradlew ${{ inputs.GRADLEW_ARGS }}
+          ./gradlew build test testDebugUnitTestCoverage sonarqube --info --warning-mode all
 
-      - name: Verify the build Gradlew application
-        run: cd ${{ inputs.SERVICE_LOCATION }} && npm run verify
-
-      - name: Set up Node.js
-        uses: actions/setup-node@v3.7.0
+      - uses: 8398a7/action-slack@v3
         with:
-          package_path: '${{ inputs.SERVICE_LOCATION }}'
-          registry-url: 'https://registry.npmjs.org/'
-
-      - name: Publish package
-        run: cd ${{ inputs.SERVICE_LOCATION }} && npm publish
+          status: ${{ job.status }}
+          fields: repo,message,author,commit,workflow,job # selectable (default: repo,message)
         env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
-
-      - name: Tag
-        run: |
-          pwd
-          cd ${{ inputs.SERVICE_LOCATION }}
-          VERSION=$(grep -o '"version": "[^"]*' package.json | sed 's/"version": "//') #Replace with the versioning strategy you prefer
-          VERSION="v${VERSION}_npm"
-          git tag $VERSION
-          git push origin $VERSION
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
+        if: failure() # Pick up events even if the job fails or is canceled.
