updated
Signed-off-by: techno-467 <prafulrakhade02@gmail.com>

diff --git a/.github/workflows/post-release-changes.yml b/.github/workflows/post-release-changes.yml
--- a/.github/workflows/post-release-changes.yml
+++ b/.github/workflows/post-release-changes.yml
@@ -66,6 +66,13 @@ jobs:
           echo "FROM_VERSION: ${{ inputs.FROM_VERSION }}"
           echo "TO_VERSION: ${{ inputs.TO_VERSION }}"
 
+      - name: Check for Conflicting Updates
+        run: |
+          if [ "${{ inputs.UPDATE_RELEASE_URL }}" = "true" ] && [ "${{ inputs.UPDATE_SNAPSHOT_URL }}" = "true" ]; then
+            echo "ERROR: Both UPDATE_RELEASE_URL and UPDATE_SNAPSHOT_URL cannot be true simultaneously."
+            exit 1
+          fi
+
       - name: Conditional Maven URL Update
         run: |
           cd .github/workflows
@@ -76,13 +83,13 @@ jobs:
           fi
 
       - name: Conditional POM Version Update
-        if: ${{ inputs.UPDATE_POM_VERSION }}
+        if: ${{ inputs.UPDATE_POM_VERSION == 'true' }}
         run: |
           if [ -z "${{ inputs.FROM_VERSION }}" ] || [ -z "${{ inputs.TO_VERSION }}" ]; then
             echo "FROM_VERSION and TO_VERSION must be provided when UPDATE_POM_VERSION is true."
             exit 1
           fi
-          echo "Updating POM versions from ${FROM_VERSION} to ${TO_VERSION}"
+          echo "Updating POM versions from ${{ inputs.FROM_VERSION }} to ${{ inputs.TO_VERSION }}"
           find . -type f -name "pom.xml" -exec sed -i "s/${{ inputs.FROM_VERSION }}/${{ inputs.TO_VERSION }}/g" {} +
 
       - name: Create Pull Request
@@ -90,7 +97,7 @@ jobs:
         with:
           commit-message: Updated Pom versions for release changes
           title: Post release changes
-          branch: releas-branch
+          branch: release-branch
           delete-branch: true
           base: ${{ inputs.BASE }}
           token: ${{ secrets.ACTION_PAT }}
